lite6:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: lite6_traj_controller
      type: position_controllers/JointTrajectoryController
      joints:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
      constraints:
          goal_time: 0.5
          stopped_velocity_tolerance: 0.05
          joint1: {trajectory: 1, goal: 0.01}
          joint2: {trajectory: 1, goal: 0.01}
          joint3: {trajectory: 1, goal: 0.01}
          joint4: {trajectory: 1, goal: 0.01}
          joint5: {trajectory: 1, goal: 0.01}
          joint6: {trajectory: 1, goal: 0.01}
      stop_trajectory_duration: 0.2
      state_publish_rate:  25
      action_monitor_rate: 10